# Generated by Django 3.2.16 on 2023-01-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_articles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default='No Data...'),
            preserve_default=False,
        ),
    ]
